### ISSUE TITLE
Mapa Mental Web 3.0

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/mapa-mental-web-3-Abraham890#1]
[Abraham_Reyes_Ortiz_Mapa_Mental_Web.3.0_6US.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Abraham890/files/8445058/Abraham_Reyes_Ortiz_Mapa_Mental_Web.3.0_6US.pdf)

**Comment by IsraelNicolas61** [comment]
17% de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
